### ISSUE TITLE
opencv error in filt when using mono camera

### ISSUE THREAD

**Issue by jvoigts** [jonnew/Oat#27]
the filt module throws an openCV error related to pixel format/ bit depth when running mono cams.

error log example: 
..
Gain set to 16.00 dB.
You cannot adjust the white balance for mono frames.Setting image parameters...
ROI set to [0 0 752 480]
Image settings configured.
frameserve[raw]: Steaming to sink raw.
frameserve[raw]: Press CTRL+C to exit.
raw completed write number: 0
[752 x 480][752 x 480]filt completed write number: 0
OpenCV Error: Assertion failed ((scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F)) in ipp_cvtColor, file /home/travis/miniconda/conda-bld/work/opencv-3.1.0/modules/imgproc/src/color.cpp, line 7646
posidet[filt->pos]: /home/travis/miniconda/conda-bld/work/opencv-3.1.0/modules/imgproc/src/color.cpp:7646: error: (-215) (scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F) in function ipp_cvtColor

this happened somewhere between
1c3bf5cbfaf219b52c2afa1b44da894f37641915 (working) and
8fcc15f6397c3218fb8d6160e82b6785b9425356 (broken)

**Comment by jonnew** [comment]
This is happening because Oat used  to all frames as 8-bit 3-channel BRG images. OpenCV provides (generally) generic algorithms for processing images across types (at least 8-bit types that are the result of most cameras). This error is a result of introducing stricter pixel typing into Oat. Oat now has enforces the concept of "color" vs "mono" pixels withing a `Frame`. Because you were acquiring from a mono camera, Oat used the Mono image format, which is 1/3 the size of the color alternative, rather than forcing the mono content into a color image. The OpenCV function used int he HSV detector is not generic and requires a color frame. This is the reason for the assertion failure. 

Clearly, relying on OpenCV's assertions is not the right ways to deal with this. So, I've attempted to move runtime pixel type checking to caught exceptions that allow destructors to be called and shared memory to be deallocated. Pixel type is now a core attribute of the `oat::Frame` type in the `program-opt-refactor` branch. Additionally, I've added `oat posidet thrsh` detector for doing amplitude based thresholding for mono frame streams. This is a huge performance benefit over using `oat posidet hsv` and only using the `value` channel for bandpass filtering (1000 1MP frames):

- `hsv`
  - real	0m4.683s
  - user	0m0.071s
  - sys	    0m0.067s


- `trsh`
  - real	0m0.545s
  - user	0m0.028s
  - sys	    0m0.012s
