### ISSUE TITLE
posisock throws "send_to: Invalid argument" error

### ISSUE THREAD

**Issue by ilodor** [jonnew/Oat#7]
After recieving a data query, the server mode of posisock gives the aforementioned error and does not respond with position data (it does nothing instead). It appears oat is failing to properly identify the sender's endpoint.

The send_to function is in line 74 in Oat/src/positionsocket/SocketWriteStream.h

**Comment by jonnew** [comment]
Honestly, I did not put too much time into figuring out what was going on here because I've been wanting to move `oat-posisock` towards a zeromq-based messaging system for a while. Commit This was a good opportunity to do that. As of b984a4079d39693ed67aaa17f6625102e3298dd2 `oat-posisock` supports two zmq_socket messaging patterns:

- PUB - send-only, asynchronous publication of positions as they are received
- REP - synchronous replies to remote requests

Usage can be seen with `oat-posisock --help` and examples are available in the /examples/posisock-to-python folder. The server-side udp functionality has been commented out of the code base until somebody really needs it. Let me know if this works out.
